### ISSUE TITLE
大牛您好，有两个问题向您请教一下

### ISSUE THREAD

**Issue by FelixAndTylor** [Angus-Liu/smilcool#14]
1，前端vue的启动命令是什么呢 npm run 什么呢？
2，后端的redis需要其脚本或者什么吗？
小弟最近在学习这方面的内容，有这两个疑问，在此先谢过大牛了

**Comment by Angus-Liu** [comment]
实际上这是一个应付毕设的半成品，redis 模块最后我去掉了。前端 smilcool-client 的 readme 文档中就有启动方式，进入 smilcool-client 目录，先运行 yarn install 安装依赖，再运行 yarn run server 运行就可以了，前提是后台 smilcool-server 已经运行，不然没有数据

**Comment by Angus-Liu** [comment]
Redis 在电脑上安装好，设置密码为 root 就可以了，实际上没有 redis 也不影响使用
